// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2Qh9wrwe6rx7v8b_VaF3uurG3_L4pMmY',
    appId: '1:293099177643:web:a974af9e18c54614e519ee',
    messagingSenderId: '293099177643',
    projectId: 'ai-app-b15d2',
    authDomain: 'ai-app-b15d2.firebaseapp.com',
    storageBucket: 'ai-app-b15d2.appspot.com',
    measurementId: 'G-BWB45JQ1EZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5ZFxhSgaTvjkgJQAHqmDRvNhEObWWOE4',
    appId: '1:293099177643:android:6876566bd55a2126e519ee',
    messagingSenderId: '293099177643',
    projectId: 'ai-app-b15d2',
    storageBucket: 'ai-app-b15d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP6NWilziQGyju3qYag-GS1_Lwtlnwo1g',
    appId: '1:293099177643:ios:c98fa285be9b53a9e519ee',
    messagingSenderId: '293099177643',
    projectId: 'ai-app-b15d2',
    storageBucket: 'ai-app-b15d2.appspot.com',
    iosBundleId: 'com.example.openAiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP6NWilziQGyju3qYag-GS1_Lwtlnwo1g',
    appId: '1:293099177643:ios:38dff1b755b1c7e9e519ee',
    messagingSenderId: '293099177643',
    projectId: 'ai-app-b15d2',
    storageBucket: 'ai-app-b15d2.appspot.com',
    iosBundleId: 'com.example.openAiApp.RunnerTests',
  );
}
